baseURL = "https://urc-kaist.github.io/"
title = "URC KAIST"
author = "gmmyung"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
theme = "tella"
enableRobotsTXT = true

# Please enable this feature if the site is available in Japanese, Chinese or Korean.
hasCJKLanguage = true

# If you're using Google Analytics, you can enable this feature.
#googleAnalytics = "UA-12345678-1"

# Disqus Comment System
#disqusShortname = ""

[markup.goldmark.renderer]
  unsafe = true

[params]

  # showBlog = true
  # mainSections = ['blog']

  googleFonts = true

  [params.logo]
    main = "img/logo/logo.jpeg"
    alt = "MR2 Logo"

    # The size parameter is the class name of tailwindcss
    # https://tailwindcss.com/
    size = "h-8 md:h-9 lg:h-10"

  [params.site]
    name = "URC KAIST"

  [params.icon]
    #If you want to use FontAwesome, set this parameter to true.
    fontawesome = true

  [params.homepage_meta_tags]
    meta_description = "We are the MR2 KAIST Rover Team."
    meta_og_title = "MR2 KAIST"
    meta_og_type = "website"
    meta_og_url = "https://urc-kaist.github.io/"
    meta_og_image = "https://urc-kaist.github.io/img/slide/autonomous_drive.png"
    meta_og_description = "We are the MR2 KAIST Rover Team."

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    identifier = "members"
    name = "Members"
    url = "/members/"
    weight = 2

  [[menu.main]]
    identifier = "products"
    name = "Projects"
    url = "/projects/"
    weight = 3

  [[menu.main]]
    identifier = "blog"
    name = "Posts"
    url = "/blog/"
    weight = 4

  [[menu.main]]
    identifier = "docs"
    name = "Docs"
    url = "/docs/"
    weight = 5

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 6

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.footer]]
    name = "Email"
    url = "mailto:mr2.kaist.rover@gmail.com"
    weight = 2

  [[menu.footer]]
    name = "Github"
    url = "https://github.com/URC-kaist"
    pre = "<i class='fa-brands fa-github text-2xl'></i>"
    weight = 3

  [[menu.footer]]
    name = "Youtube"
    url = "https://www.youtube.com/@MR2KAISTRoverTeam"
    pre = "<i class='fa-brands fa-youtube text-2xl'></i>"
    weight = 4

  [[menu.footer]]
    name = "Instagram"
    url = "https://www.instagram.com/urc_mr2/"
    pre = "<i class='fa-brands fa-instagram text-2xl'></i>"
    weight = 5
